version: "3.7"

volumes:
  redis-local:
  postgres-local:

services:
  db:
    image: postgres:latest
    ports:
      - 5432:5432
    env_file:
    - docker.env
    volumes:
      - postgres-local:/var/lib/postgresql/data

  pgweb:
    image: sosedoff/pgweb
    restart: on-failure
    ports:
      - 5433:8081
    environment:
      - DATABASE_URL=postgres://admin:admin@db:5432/nestapp?sslmode=disable
    depends_on:
      - db
    healthcheck:
      disable: true
